name: LeopardToolKit Email 

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
    - name: Install dependencies
      run: dotnet restore LeopardToolKit.Email.sln
    - name: Build
      run: dotnet build LeopardToolKit.Email.sln --configuration Release --no-restore
      
    - name: Publish NuGet
      uses: rohith/publish-nuget@v2.2.1
      with:
        PROJECT_FILE_PATH: LeopardToolKit.Email/LeopardToolKit.Email.csproj
        TAG_COMMIT: false
        VERSION_FILE_PATH: LeopardToolKit.Email/LeopardToolKit.Email.csproj
        VERSION_REGEX: <Version>(.*)<\/Version>
        NUGET_KEY: ${{ secrets.NugetKey }} 

